import localFont from "next/font/local";
import "./globals.css";

const switzer = localFont({
  src: [
    {
      path: '../fonts/switzer/Switzer-Regular.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../fonts/switzer/Switzer-Medium.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../fonts/switzer/Switzer-Semibold.woff2',
      weight: '600',
      style: 'normal'
    },
    {
      path: '../fonts/switzer/Switzer-Bold.woff2',
      weight: '700',
      style: 'normal'
    }
  ],
  variable: '--font-switzer',
  display: 'swap',
  preload: true
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${switzer.variable} antialiased font-switzer`}
      >
        {children}
      </body>
    </html>
  );
}
